# Generated by Django 5.0.3 on 2024-03-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='count',
        ),
        migrations.AddField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.item'),
            preserve_default=False,
        ),
    ]
